# Services
services:
            
    # S7M - Call Content Bundle
    seven_manager.admin.pages.boilerplate:
        class: SevenManagerBundle\Admin\Pages\BoilerplateAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Boilerplate, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Boilerplate', label: Boilerplate }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.homepage:
        class: SevenManagerBundle\Admin\Pages\HomepageAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Homepage, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.homepage }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.node:
        class: SevenManagerBundle\Admin\Pages\NodeAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Node, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.node }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.page:
        class: SevenManagerBundle\Admin\Pages\PageAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Page, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.post:
        class: SevenManagerBundle\Admin\Pages\PostAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Post, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.post }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.article:
        class: SevenManagerBundle\Admin\Pages\ArticleAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Article, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.article }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.gallery:
        class: SevenManagerBundle\Admin\Pages\GalleryAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Gallery, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.gallery }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.pages.form:
        class: SevenManagerBundle\Admin\Pages\FormAdmin
        arguments: ['', SevenManagerBundle\Document\Pages\Form, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Pages', label: seven_manager.shared.labels.form }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.containers.slideshow:
        class: SevenManagerBundle\Admin\Containers\SlideshowAdmin
        arguments: ['', SevenManagerBundle\Document\Containers\Slideshow, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Containers', label: Slideshow }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.blocks.slideone:
        class: SevenManagerBundle\Admin\Blocks\ImageOneAdmin
        arguments: ['', SevenManagerBundle\Document\Blocks\ImageOne, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Sbt + Lbl + Img }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.blocks.linkone:
        class: SevenManagerBundle\Admin\Blocks\LinkOneAdmin
        arguments: ['', SevenManagerBundle\Document\Blocks\LinkOne, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Lbl + Lnk }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.collections.title.sub.desc.image.target:
        class: SevenManagerBundle\Admin\Collections\TitleSubDescImageTargetAdmin
        arguments: ['', SevenManagerBundle\Document\Collections\TitleSubDescImageTarget, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Sbt + Txt }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.blocks.title.image:
        class: SevenManagerBundle\Admin\Blocks\TitleImageAdmin
        arguments: ['', SevenManagerBundle\Document\Blocks\TitleImage, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Img }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.collections.font.title.desc.target:
        class: SevenManagerBundle\Admin\Collections\FontTitleDescTargetAdmin
        arguments: ['', SevenManagerBundle\Document\Collections\FontTitleDescTarget, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Lbl + Txt + Lnk }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.blocks.title.text:
        class: SevenManagerBundle\Admin\Blocks\TitleTextAdmin
        arguments: ['', SevenManagerBundle\Document\Blocks\TitleText, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Blocks', label: Ttl + Txt }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager.admin.menu.menu:
        class: SevenManagerBundle\Admin\Menu\MenuAdmin
        arguments: ['', SevenManagerBundle\Document\Menu\Menu, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'S7M - Menu', label: Menu }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]