services:

    # Seven Manager - Initializer
    seven_manager.pages.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - Seven Manager - Initializer
            - ["/seven-manager", "/seven-manager/boilerplate", "/seven-manager/homepage", "/seven-manager/page", "/seven-manager/article", "/seven-manager/node", "/seven-manager/post", "/seven-manager/form", "/seven-manager/gallery", "/seven-manager/slideshow", "/seven-manager/images", ]
        tags:
            - { name: doctrine_phpcr.initializer }

    seven_manager.fixtures.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - Seven Manager - Fixtures Initializer
            - ["/seven-manager/fixtures/pages", "/seven-manager/fixtures/posts", "/seven-manager/fixtures/content", "/seven-manager/fixtures/routes", "/seven-manager/fixtures/type-a", "/seven-manager/fixtures/type-b", "/seven-manager/fixtures/type-c"]
        tags:
            - { name: doctrine_phpcr.initializer }