# Seven Manager - Managers
services:
    seven_manager.station_manager:
        class:  SevenManagerBundle\Manager\StationManager

    seven_manager.parent_manager:
        class:  SevenManagerBundle\Manager\ParentManager
