# Redirect to default language
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: true

# Homepage
seven_manager_pages_homepage:
    path:     /{locale}
    defaults: { _controller: SevenManagerBundle:Homepage:index, locale: "%locale%" }
    requirements: { locale: en|fr|de }

# Fixtures
seven_manager_fixtures_homepage:
    path:     /hello/{name}
    defaults: { _controller: SevenManagerBundle:Default:index }